/*

 SKY_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : sky_tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __sky_map_h_INCLUDE
#define __sky_map_h_INCLUDE

#define sky_mapWidth 32
#define sky_mapHeight 32
#define sky_mapBank 0

#define sky_map sky_mapPLN0
extern const unsigned char sky_mapPLN0[];

#endif

/* End of SKY_MAP.H */
